import { aiRequestFor, aiProviderForKey, aiPromptText } from "../app.v56.js";
let fails = 0;
const ck = (c, n) => { if (c) console.log("PASS " + n); else { fails++; console.log("FAIL " + n); } };
const pay = { text: "prompt", images: ["QUJD"] };
const g = aiRequestFor("groq", "gsk_x", "meta-llama/llama-4-scout-17b-16e-instruct", pay);
ck(g.url === "https://api.groq.com/openai/v1/chat/completions", "groq-url");
ck(g.headers.Authorization === "Bearer gsk_x", "groq-auth");
ck(Array.isArray(g.body.messages[0].content) && g.body.messages[0].content[1].image_url.url.startsWith("data:image/png;base64,"), "groq-vision-parts");
const gt = aiRequestFor("groq", "gsk_x", "llama-3.3-70b-versatile", pay);
ck(typeof gt.body.messages[0].content === "string" && gt.vision === false, "groq-textonly-fallback");
const o = aiRequestFor("openrouter", "sk-or_y", "google/gemini-2.0-flash-exp:free", pay);
ck(o.url === "https://openrouter.ai/api/v1/chat/completions" && o.headers["X-Title"] === "Radiology report AI", "openrouter-url-title");
const gm = aiRequestFor("gemini", "AIza z", "gemini-2.5-flash", pay);
ck(gm.url.includes("generativelanguage.googleapis.com") && gm.url.includes("key=AIza%20z") && gm.body.contents[0].parts.length === 2, "gemini-native");
ck(g.body.response_format.type === "json_object" && o.body.response_format.type === "json_object", "json-mode");
ck(aiProviderForKey("gsk_abc") === "groq" && aiProviderForKey("sk-or-x") === "openrouter" && aiProviderForKey("AIza1") === "gemini", "key-shapes");
ck(aiProviderForKey("sk-proj-JG4t") === "openai-unsupported" && aiProviderForKey("sk-plain") === "openai-unsupported", "openai-rejected");
const stN = { modality: "MR", frames: [1], meta: {}, report: { notes: "post-op lumbar fixation 6y, LBP + right radiculopathy" }, triage: { score: 0.001, priority: "routine", context: "unknown", reasons: [] } };
const pt = aiPromptText(stN);
ck(pt.includes("RAW CLINICAL NOTES") && pt.includes("post-op lumbar fixation 6y"), "notes-in-prompt");
ck(pt.includes("<anat></anat>") && pt.includes("do not repeat any finding"), "prompt-rules");
console.log(fails ? "AI TEST FAIL " + fails : "AI TEST PASS (11)");
