import { drawFrame } from "../app.v80.js";
let fails = 0;
const ck = (c, n) => { if (!c) { fails++; console.log("FAIL " + n); } };
function fakeCanvas() {
  let w = 0, h = 0, sets = 0;
  const ctx = { createImageData: (W, H) => ({ data: new Uint8ClampedArray(W * H * 4) }), putImageData: () => {} };
  return {
    get width() { return w; }, set width(v) { w = v; sets++; },
    get height() { return h; }, set height(v) { h = v; sets++; },
    getContext: () => ctx, sets: () => sets,
  };
}
const px = { w: 64, h: 64, data: new Uint16Array(64 * 64).map((_, i) => i % 997) };
const c = fakeCanvas();
drawFrame(c, px, "auto", "MR");
ck(c.sets() === 2, "first draw sizes canvas once");
drawFrame(c, px, "auto", "MR");
ck(c.sets() === 2, "second draw must NOT re-clear canvas (flicker guard)");
ck(px.__win && px.__win.k === "auto|MR", "window/level memo stored per frame");
const src = await import("node:fs").then((fs) => fs.readFileSync(new URL("../app.v80.js", import.meta.url), "utf-8"));
ck(src.includes("if (viewKey !== vKey)"), "view preserved across slice scroll");
ck(src.includes("Math.round(vx)"), "integer pan (no subpixel shimmer)");
ck(src.includes("requestAnimationFrame(() => { showRaf = 0; show(v); })"), "scroll redraws coalesced via rAF");
ck(!src.includes("sampleMean"), "GPU readback forensic removed from scroll path");
ck(src.includes("pixels.__img"), "ImageData cache for slice revisit");
ck(src.includes("if (ov.width !== f0.w)"), "overlay resize guarded");
ck(!src.includes("vpR.addEventListener"), "conflicting dblclick listener removed");
ck(src.includes("if (vk <= 1.01 && !fsNow()) { vx = 0; vy = 0; }"), "no floating pan below zoom 1 (pan allowed in fullscreen only)");
ck(!src.includes("Math.max(1, Math.min(4,"), "fit allowed below 1x on phones");
ck(src.includes("• ${APP_BUILD}"), "meta line uses APP_BUILD (never a stale literal)");
ck(src.includes("window.innerHeight"), "fit accounts for available height (controls stay on screen)");
ck(src.includes("controllerchange"), "open tabs self-heal when a new SW takes control");
const sws = await import("node:fs").then((fs) => fs.readFileSync(new URL("../sw.v80.js", import.meta.url), "utf-8"));
ck(sws.includes("self.skipWaiting()") && sws.includes("clients.claim()"), "SW activates immediately and claims clients");
ck(sws.includes("app.v80.js"), "SW precache list matches current build");
ck(src.includes("function sliceFitFor(f)"), "per-slice fit: every slice fills the viewport");
ck(!src.includes("for (const fr of current.frames) { if (fr.w > maxW)"), "no series-wide scaling (was shrinking mixed-dim slices)");
ck(src.includes("function releaseWatch()"), "stale tabs auto-reload via release watchdog");
ck(src.includes("rrai-rw-"), "auto-reload guarded once per build");
ck(src.includes("ملاءمة=${fitK.toFixed(2)}"), "meta line exposes live fit factor for forensics");
ck(src.includes("card.requestFullscreen"), "native fullscreen with graceful fallback");
ck(src.includes("fs-fake"), "pseudo-fullscreen fallback for browsers without API");
ck(src.includes("const fs = fsNow()"), "fit honors fullscreen height");
ck(src.includes("const ch = vp ? (vp.clientHeight || 0) : 0;"), "fullscreen cover measured from real viewport height");
ck(src.includes("Math.min(cw / (f.w || 1), chh / (f.h || 1))"), "fullscreen CONTAIN: whole image visible at max screen size (never cropped)");
ck(src.includes("function fsArm()") && !src.includes("fsBarShow(false); }, 3000)"), "fullscreen controls stay visible (no auto-hide)");
ck(src.includes("qwen/qwen3.8-27b"), "groq list uses live Sep-2026 free models (retired llama ids removed)");
ck(src.includes("new AbortController()"), "AI requests time out at 45s instead of hanging");
ck(src.includes("const provName = provider === \"groq\" ? \"Groq\""), "consent dialog names the ACTUAL provider (no stale Gemini wording)");
ck(!src.includes("to Google Gemini for this one request?"), "hardcoded Gemini consent text removed");
ck(src.includes("console.groq.com → API Keys (gsk…)"), "missing-key guidance points to card-free Groq");
ck(src.includes("You are a CONSULTANT RADIOLOGIST assistant"), "prompt demands consultant-grade structured draft");
ck(src.includes("c.toDataURL(\"image/jpeg\", 0.9)"), "renders sent at 768px JPEG (sharper vision input)");
ck(src.includes("technique: String(obj.technique || \"\").trim()"), "AI technique stored with the report");
ck((await import("node:fs").then((fs) => fs.readFileSync(new URL("../docx.v80.js", import.meta.url), "utf-8"))).includes("const compTech = comp && comp.technique"), "Word export uses AI technique when present");
ck(src.includes("fileToJpegB64") && src.includes(".concat(aiExtraImgs).slice(0, 8)"), "physician screenshots join the request (max 8 images)");
ck(src.includes("attached screenshot(s)"), "consent names attached screenshots");
ck(src.includes("EQUAL weight to the slice renders"), "prompt gives attached screenshots primary-evidence weight");
ck(src.includes("rrai-self-heal") && src.includes("location.reload()"), "boot error self-heals once (purge stale caches + unregister + reload)");
ck(sws.includes("rrai-sw-updated"), "SW notifies clients after activate");
ck(src.includes("function clampPan()"), "drag pan clamped so image cannot be lost");
ck(src.includes("vk <= 1.01 && fsNow()"), "vertical swipe scrolls slices inside fullscreen");
ck(src.includes("let pinch0 = 0, k0 = 1, moved = false, swAccum = 0;"), "swipe accumulator reset per gesture");
ck(src.includes("} else if (ptrs.size === 1 && vk > 1.01) {"), "drag pan retained when zoomed");
ck(src.includes("wr.style.height = stH + \"px\""), "fixed stage box (no layout jump on mixed-dim series)");
ck(src.includes("ov.style.inset = \"auto\""), "overlay box tracks canvas inside stage");
ck(src.includes("min-width: 900px"), "height cap only on desktop layouts (phones keep width fit)");
ck((src.match(/const r = \$\("frame"\)\.getBoundingClientRect\(\);/g)||[]).length === 2, "pointer math uses canvas box (stage-safe)");
const ui = await import("node:fs").then((fs) => fs.readFileSync(new URL("../ui.v80.html", import.meta.url), "utf-8"));
const startHtml = (await import("node:fs")).readFileSync(new URL("../start.html", import.meta.url), "utf-8");
ck(startHtml.includes("ev.persisted") && startHtml.includes("rrai-sw-updated"), "bootstrap reloads on bfcache restore and on SW update");
ck(src.includes("if (useImages && !cfg.vision[model] && !cfg.native) continue;"), "images never silently dropped: text-only models skipped while images pending");
ck(src.includes("المسودة من السياق/الملاحظات فقط"), "blind fallback draft is explicitly labeled");
ck(src.includes("function renderBank") && ui.includes("id=\"bank-list\""), "phrase bank rendered per study region");
ck(!ui.includes("data-sent=\"Post-operative changes are noted"), "static spine-only bank removed from UI");
ck(src.includes("or any adequacy comment anywhere including IMPRESSION"), "prompt bans image-adequacy comments");
ck(src.includes("while (totalB64 > 3500000 && images.length > 6)"), "oversized payloads shed extra screenshots before sending");
ck(src.includes("سبب الفشل: "), "blind fallback shows the actual vision failure reason");
ck(src.includes("prefillComposer(current);\n    renderBank(current);"), "phrase bank populated at boot for restored study");
ck(src.includes(") + \" — \" + APP_BUILD;"), "bank header shows region + build marker for field proof");
ck(src.includes("/^(AIza|AQ\\.)/i.test(k)"), "new AQ-format Gemini keys auto-detected");
ck(src.includes("!cfg.vision[model] && !cfg.native"), "Gemini native models treated as vision-capable");
ck(src.includes("Send up to 6 slice renders") && src.includes("while (totalB64 > 3500000 && images.length > 6)"), "six evenly spaced renders, 8-image cap with size shedding");
ck(src.includes("function setupTemplates") && ui.includes("id=\"tpl-list\""), "settings icon with normal/pathology template library");
ck((await import("node:fs").then((fs) => fs.readFileSync(new URL("../docx.v80.js", import.meta.url), "utf-8"))).includes("paraBold(\"• \" + String(bullets[bi2]).replace"), "Word impression bullets bold-parsed and de-duplicated");
ck(src.includes("function techniqueFor"), "deterministic TECHNIQUE generator with sequence catalog");
ck(src.includes('technique: String(obj.technique || "").trim() || techniqueFor(study)'), "AI draft never leaves technique empty");
ck((await import("node:fs").then((fs) => fs.readFileSync(new URL("../docx.v80.js", import.meta.url), "utf-8"))).includes("compTech || techniqueFor(study)"), "Word technique falls back to catalog, not contradictory boilerplate");
ck(ui.includes("id=\"app-logo\"") && ui.includes("./icons/logo.png"), "brand logo rendered in the header");
ck(sws.includes("./icons/logo.png"), "logo precached for offline branding");
ck(ui.includes("id=\"ai-extra\"") && ui.includes("id=\"ai-extra-count\""), "UI exposes the extra-screenshot input");
ck(ui.includes('id="zoom-reset" class="ghost">\u0645\u0644\u0627\u0621\u0645\u0629</button>'), "fit button labeled clearly (was cryptic 1:1)");
ck(ui.includes('id="zscale"'), "live zoom scale indicator present");
ck(ui.includes('id="fs-toggle"'), "fullscreen button present in viewer controls");
ck(ui.includes("#viewer-card:fullscreen #viewport { position:absolute; inset:0; width:100%; height:100%; border-radius:0; display:flex; align-items:center; justify-content:center; }"), "fullscreen viewport = whole screen, centered");
ck(ui.includes("#viewer-card:fullscreen.fs-hide .controls { opacity:0; pointer-events:none; }"), "controls auto-hide overlay in fullscreen");
ck(ui.includes("#viewer-card:fullscreen #viewport { position:absolute; inset:0; width:100%; height:100%; border-radius:0; display:flex; align-items:center; justify-content:center; }"), "fullscreen image centered both axes");
ck(src.includes("vk = 2; centerOn"), "dblclick zoom tempered to x2 (less blur shock)");
ck(src.includes("const zs = $(\"zscale\")"), "applyView publishes live scale");
ck(!ui.includes("image-rendering:pixelated"), "nearest-neighbor shimmer removed from viewer");
ck(src.includes("cv.style.width = Math.round(f.w * fitK)"), "explicit fit width (no layout/scale mismatch crop)");
ck(ui.includes("transform-origin:center"), "center-origin user zoom (symmetric crop)");
ck(src.includes("const Ox = r.width / (2 * vk)"), "centroid anchor for center origin");
ck(src.includes("const s = (f0 && r.width / f0.w) || vk"), "measure math uses true display scale");
console.log(fails ? "VIEWER TEST FAIL " + fails : "VIEWER TEST PASS (89)");
