services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    ports:
      - "4242:4242"
    volumes:
      - orthanc-db:/var/lib/orthanc/db
      - ./docker/orthanc.json:/etc/orthanc/orthanc.json:ro
    restart: unless-stopped
  rrai-edge:
    depends_on:
      - orthanc
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  orthanc-db:
